name: Demo delete
on: delete

jobs:
  branch-delete:
    uses: navikt/flex-github-actions-workflows/.github/workflows/demo-delete.yml@testljvdf
    permissions:
      id-token: write
      contents: "read"
    with:
      base-path: syk/sykepenger
